### ISSUE TITLE
Enhance confidence by listing supported case

### ISSUE THREAD

**Issue by Yvem** [lukechilds/when-dom-ready#4]
correctly detecting dom ready is not trivial.

I'm not confident (no offense) with your nice lib unless it lists in the README the most common pain points:
- browser compatibility ?
- what if loaded and called after dom ready happened ? Will it trigger ?
- exact concept of dom ready ?

**Comment by Yvem** [comment]
Thanks ! I'm really thinking of using your lib.

**Comment by lukechilds** [comment]
Good point, browser support is good and yes, it still triggers if DOM is already loaded.

Exact concept of DOM ready is:

- if `document.readyState` is already `interactive` or `complete`, resolve on next tick
- otherwise, resolve on the `DOMContentLoaded` event

([relevant code](https://github.com/lukechilds/when-dom-ready/blob/1284c587014da35189c4636039277c4573a111ae/src/index.js#L20-L24))

Thanks for the suggestion, I'll add this info to the readme 👍

**Comment by lukechilds** [comment]
@Yvem Done: https://github.com/lukechilds/when-dom-ready#browser-compatibility

Also added a line to the description mentioning the Promise will still resolve if DOM is loaded.

**Comment by Yvem** [comment]
This is perfect. Integrating it to my stack ;)
